spring:
  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:db/changelog/db.changelog-master.yml
    default-schema: public

  docker:
    compose:
      lifecycle-management: start_and_stop
      stop:
        command: down
      readiness:
        wait: always