###
GET http://localhost:8080/api/currencies

###
POST http://localhost:8080/api/currencies
Content-Type: application/json

{
  "code": "TTT",
  "fullName": "Tst",
  "sign": "T"
}

###
@code =EUR
GET http://localhost:8080/api/currency/{{code}}

###
GET http://localhost:8080/api/exchangeRates

###
@baseCurrencyId =1
@targetCurrencyId =2
GET http://localhost:8080/api/exchangeRate/{{baseCurrencyId}}/{{targetCurrencyId}}

###
POST http://localhost:8080/api/exchangeRates
Content-Type: application/json

{
  "baseCurrencyId": 1,
  "targetCurrencyId": 2,
  "rate": 50.1
}