###
GET http://localhost:8080/api/currencies

###
POST http://localhost:8080/api/currencies
Content-Type: application/json

{
  "code": "RUB",
  "fullName": "Russian Ruble",
  "sign": "₽"
}

###
@code =EUR
GET http://localhost:8080/api/currency/{{code}}

###
GET http://localhost:8080/api/exchangeRates

###
@baseCurrencyCode =EUR
@targetCurrencyCode =USD
GET http://localhost:8080/api/exchangeRate/{{baseCurrencyCode}}/{{targetCurrencyCode}}

###
POST http://localhost:8080/api/exchangeRates
Content-Type: application/json

{
  "baseCurrencyCode": "USD",
  "targetCurrencyCode": "RUB",
  "rate": 11.2
}