CREATE DATABASE project_3;
CREATE SCHEMA project_3;
CREATE TABLE c_currencies
(
    c_id        serial PRIMARY KEY,
    c_code      varchar UNIQUE NOT NULL,
    c_full_name varchar        NOT NULL,
    c_sign      varchar NOT NULL
);

CREATE TABLE e_exchange_rates
(
    e_id                 integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    e_base_currency_id   integer       NOT NULL REFERENCES c_currencies (c_id),
    e_target_currency_id integer       NOT NULL REFERENCES c_currencies (c_id),
    e_rate               decimal(8, 6) NOT NULL
);

CREATE UNIQUE INDEX idx_currency ON e_exchange_rates (e_base_currency_id, e_target_currency_id);
